Correct tenant index removal on rollback
ActiveRecord does not know which index to remove
if we do not use the column name in `remove_index`

```
$ bin/rails db:rollback
== 20250321193206 AddTenantIdToSolidusTables: reverting =======================
-- remove_index("spree_addresses")
bin/rails aborted!
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

No name or columns specified
/home/user/my_store/db/migrate/20250321193206_add_tenant_id_to_solidus_tables.solidus_acts_as_tenant.rb:101:in `block in down'
/home/user/my_store/db/migrate/20250321193206_add_tenant_id_to_solidus_tables.solidus_acts_as_tenant.rb:100:in `each'
/home/user/my_store/db/migrate/20250321193206_add_tenant_id_to_solidus_tables.solidus_acts_as_tenant.rb:100:in `down'

Caused by:
ArgumentError: No name or columns specified (ArgumentError)

          raise ArgumentError, "No name or columns specified" if checks.none?
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```